### ISSUE TITLE
Does not compile on stable

### ISSUE THREAD

**Issue by samhh** [neon64/chrome-native-messaging#1]
```
   Compiling chrome_native_messaging v0.1.1
error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/chrome_native_messaging-0.1.1/src/lib.rs:3:1
  |
3 | #![feature(macro_reexport)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `chrome_native_messaging`.
```

Fails to compile on Rust 1.22.1 stable, succeeds on 1.24.0 nightly.

If this is intended it should be mentioned in README, and if it isn't then it should be fixed.

Also I was wondering if you have any examples with this project laying around? :-) Cheers!

**Comment by neon64** [comment]
Back when I wrote this library, I probably didn't care about unstable features as I was using the nightly compiler by default, however I understand that compiling on stable is very important for a lot of people.

the `macro_reexport` feature was only used as a convenience, so that you didn't have to write the following in your own code:
```
#[macro_use]
extern crate serde_json;
```

I think what I can do, is only use that feature if on nightly, and add something to the docs explaining that you need to add the two lines above ^ if you're on stable.

**Comment by neon64** [comment]
This should be fixed in version 0.1.2. Let me know if it isn't.

**Comment by samhh** [comment]
Fixed, thanks!
